/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vigenere;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lengo
 */
public class fVigenere extends javax.swing.JFrame {

    /**
     * Creates new form fVigenere
     */
    public fVigenere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPt = new javax.swing.JTextArea();
        txtKhoa = new javax.swing.JTextField();
        btnEn = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnMo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Khóa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Cipher Text");

        txtPt.setColumns(20);
        txtPt.setRows(5);
        jScrollPane1.setViewportView(txtPt);

        btnEn.setText("Encrypt");
        btnEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnActionPerformed(evt);
            }
        });

        btnGhi.setText("Ghi file");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        txtCt.setColumns(20);
        txtCt.setRows(5);
        jScrollPane2.setViewportView(txtCt);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Thuật toán mã hóa Vigenere Cipher");

        btnMo.setText("Mở file");
        btnMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Plain Text");

        btnDe.setText("Decrypt");
        btnDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(txtKhoa)
                    .addComponent(jScrollPane2))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnEn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGhi)
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(btnDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMo)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEn)
                    .addComponent(btnGhi))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMo)
                    .addComponent(btnDe))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnActionPerformed
        // TODO add your handling code here:
        int table[][] = new int[26][26];
        for (int i = 0; i < 26; i++) {
            for (int j = 0; j < 26; j++) {
                table[i][j] = (i + j) % 26;
            }
        }

        String plainText = txtPt.getText();//lấy chuỗi cần mã hóa
        String key = (txtKhoa.getText()).toUpperCase();//lấy chuỗi khóa sau đó in hoa
        String result = "";//chuỗi kết quả sau mã hóa
        int keyIndex = 0;//chỉ số khóa

        for (int i = 0; i < plainText.length(); i++) {
            int value;//lưu mã ascii của kí tự đã mã hóa
            char kChar = key.charAt(keyIndex);//lấy kí tự của khóa tại vị trí keyindex
            int ch2 = ((int) kChar) - 65;//lấy mã ascii của key
            //JOptionPane.showMessageDialog(null, ch2);
            char ch = plainText.charAt(i);
//            kiểm tra kí tự đặc biệt và dấu cách
            if (!(65 <= (int) ch && (int) ch <= 90) && !(97 <= (int) ch && (int) ch <= 122)) {
                result += ch;
                keyIndex--;
            }
            if (Character.isUpperCase(ch)) {
                int ch1 = ((int) ch) - 65;
                value = table[ch1][ch2];
                result += (char) (value + 65);
                //JOptionPane.showMessageDialog(null, ch1 + " "+ value +" "+ result);
            } else if (Character.isLowerCase(ch)) {
                int ch1 = ((int) ch) - 97;
                value = table[ch1][ch2];
                result += (char) (value + 97);
                //JOptionPane.showMessageDialog(null, ch1 + " "+ value +" "+ result);
            }
            keyIndex++;
            if (keyIndex >= key.length()) {
                keyIndex = 0;
            }
        }
        txtCt.setText(result);
    }//GEN-LAST:event_btnEnActionPerformed

    private void btnDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeActionPerformed
        // TODO add your handling code here:
        int table[][] = new int[26][26];
        for (int i = 0; i < 26; i++) {
            for (int j = 0; j < 26; j++) {
                table[i][j] = (i + j) % 26;
            }
        }

        String cipherText = txtCt.getText();//lấy chuỗi cần mã hóa
        String key = (txtKhoa.getText()).toUpperCase();//lấy chuỗi khóa sau đó in hoa
        String result = "";//chuỗi kết quả sau mã hóa
        int keyIndex = 0;//chỉ số khóa

        for (int i = 0; i < cipherText.length(); i++) {
            char kChar = key.charAt(keyIndex);//lấy kí tự của khóa tại vị trí keyindex
            int ch2 = ((int) kChar) - 65;//lấy mã ascii của key
            //JOptionPane.showMessageDialog(null, ch2);
            char ch = cipherText.charAt(i);
            //kiểm tra kí tự đặc biệt và dấu cách
            if (!(65 <= (int) ch && (int) ch <= 90) && !(97 <= (int) ch && (int) ch <= 122)) {
                result += ch;
                keyIndex--;
            }
            for (int j = 0; j < 26; j++) {
                if (Character.isUpperCase(ch)) {
                    if (table[ch2][j] == (int) ch - 65) {
                        char ch1 = (char) (j + 65);
                        result += ch1;
                    }
                    //JOptionPane.showMessageDialog(null, ch1 + " "+ value +" "+ result);
                } else if (Character.isLowerCase(ch)) {
                     if (table[ch2][j] == (int) ch - 97) {
                        char ch1 = (char) (j + 97);
                        result += ch1;
                     }
                }
            }
            keyIndex++;
            if (keyIndex >= key.length()) {
                keyIndex = 0;
            }
            txtPt.setText(result);
        }
    }//GEN-LAST:event_btnDeActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        try{
            BufferedWriter bw = null;
            String filename = "D:\\dulieu.txt";
            String s = txtCt.getText();
            bw = new BufferedWriter(new FileWriter(filename));
            bw.write(s);
            bw.close();
            JOptionPane.showMessageDialog(null, "Đã ghi file thành công!!!!");
        }catch(IOException ex){
            Logger.getLogger(fVigenere.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoActionPerformed
        // TODO add your handling code here:
        try{
                BufferedReader br = null;
                String filename = "D:\\dulieu.txt";
                br = new BufferedReader(new FileReader(filename));
                StringBuffer sb = new StringBuffer();
                JOptionPane.showMessageDialog(null, "Đã mở file thành công!!!");
                char[] ca = new char[5];
                while(br.ready()){
                    int len = br.read(ca);
                    sb.append(ca, 0, len);
                }
                br.close();
                String chuoi = sb.toString();
                txtCt.setText(chuoi);
        }catch(IOException ex){
            Logger.getLogger(fVigenere.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fVigenere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fVigenere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fVigenere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fVigenere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fVigenere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDe;
    private javax.swing.JButton btnEn;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnMo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtCt;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextArea txtPt;
    // End of variables declaration//GEN-END:variables
}
